---
title: "Inverse_Propensity_Score"
author: "RuiLiang&rl2886"
date: "11/14/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Libraries
library(glmnet)
library(tidyverse)
```

## Data Preprocessing

```{r }
# Load the data
highDim<-read.csv(file ='../data/highDim_dataset.csv')
lowDim<-read.csv(file ='../data/lowDim_dataset.csv')

# Split into x, A and y
hY<-highDim$Y
hA<-highDim$A
hX<-as.matrix(highDim[,-c(1,2)])

lY<-lowDim$Y
lA<-lowDim$A
lX<-as.matrix(lowDim[,-c(1,2)])

```

## IPW

```{r }
# IPW
# Setting alpha = 1 implements lasso regression
lambdas <- 10^seq(2, -3, by = -.1)
lasso_hd <- cv.glmnet(hX, hY, alpha = 1, lambda = lambdas, standardize = TRUE, nfolds = 5)
lasso_ld <- cv.glmnet(lX, lY, alpha = 1, lambda = lambdas, standardize = TRUE, nfolds = 5)

# Calculate the propensity score 
lasso_model_hd <- glmnet(hX, hY, alpha = 1, lambda = lasso_hd$lambda.min, standardize = TRUE)
lasso_model_ld <- glmnet(lX, lY, alpha = 1, lambda = lasso_ld$lambda.min, standardize = TRUE)
propensity_hd = predict(lasso_model_hd, s = lasso_hd$lambda.min, newx = hX)
propensity_ld = predict(lasso_model_ld, s = lasso_ld$lambda.min, newx = lX)

# Calculate the weights
weight_hd = 1 / propensity_hd * hA + 1 / (1 - propensity_hd) * (1 - hA)
weight_ld = 1 / propensity_ld * lA + 1 / (1 - propensity_ld) * (1 - lA)
resampled_lowDim <- lowDim %>%
      mutate(propensity_ld = propensity_ld,
             weight_ld = weight_ld,
             Y_Weight = Y*weight_ld)
resampled_highDim <- highDim %>%
      mutate(propensity_hd = propensity_hd,
             weight_hd = weight_hd,
             Y_Weight= Y*weight_hd )


# Estimate ATE
ATE<-function(data){
      ATE<-1/nrow(data)*(sum(data[data$A==1,"Y_Weight"])-sum(data[data$A==0,"Y_Weight"]))
      return(ATE)
}

ATE_highDim<-ATE(resampled_highDim)
ATE_lowDim<-ATE(resampled_lowDim)
matrix(c(ATE_highDim,ATE_lowDim),nrow = 1, dimnames = list(c("ATE"), c("highDim","lowDim")))
```


